### ISSUE TITLE
Add notes on use without npm or yarn

### ISSUE THREAD

**Issue by kriscarle** [maphubs/mapbox-gl-regex-query#1]

**Comment by kriscarle** [comment]
There is a built file in the dist folder that can be loaded in the browser directly. We can add a quick note to the readme about that.

**Comment by politvs** [comment]
@kriscarle perfect, I'll try it!!

The quick note would be a nice touch for people like me, though :)

**Comment by kriscarle** [comment]
No problem, looks like I used the name RegexQuery in browserify, so that is what to use after you load it. I updated the README with some notes.

```html
<script src="mapbox-gl-regex-query.js"></script>
<script>
...
//create a mapbox map as usual...
//then run a query
RegexQuery.querySourceFeatures(sourceID, filter, map);
...
</script>
```

**Comment by politvs** [comment]
Can't put it to work :(

You can take a look to what my code looks like here:

https://stackoverflow.com/questions/44345532/set-filter-by-partial-string-in-mapbox-gl/44360743

I can provide source code, though.

Trying to filter by "tags" returns empty array, same for time. Maybe I'm doing something wrong, my js is not as good as it should be...

```
    var results = RegexQuery.querySourceFeatures('gsa2016',
    {
      source: 'gsa2016',
      filter: ['all',
        ['~=', 'time', '/.*2016.*/g']
      ]
    },
    map);
    console.log(results);
```

Layers are added like this, by the way, one for each year in an array:

```
                        map.addLayer({
                            'id': year,
                            'type': 'circle',
                            'source': layerIdPrefix + year, 
                            'layout': { 'visibility': 'visible' },
                            'paint': {
//                                'circle-radius': 6,
                                'circle-radius': { stops: [[8, 10], [11, 8], [16, 6]] },
                                'circle-color': rgbCircleColor, 
//                                'circle-opacity': 0.6 // Give it a little transparency
                                'circle-opacity': { stops: [[3, 0.2], [10, 0.7], [15, 1]] }, 
                                'circle-stroke-width': 1,
                                'circle-stroke-color': '#000000', 
                                'circle-stroke-opacity':  { stops: [[3, 0.2], [10, 0.7], [15, 1]] }
                            }
                        });
```

Any hint?

**Comment by kriscarle** [comment]
Now that I see your code, I don't think you need to use this hack.

Since you have access to the raw GeoJSON data, just insert a unique id into the properties of each feature, do the search on the plain JSON data, and then use the filter as supported in the API, `['in', 'id', 1, 2, 3]`. 

You could try something like this http://defiantjs.com/ for faster searching if your GeoJSON is large enough to need it. 

This code is mainly for when you need runtime queries that you don't know ahead of time (e.g. user typing in a search box) and don't have all the data already in the browser, for example, to search inside vector tile data sources without needing to also download the data as GeoJSON, or use a server-side query service.

Also if you goal is just to filter by years, there is a "year" column in your data. Just do `filter: ['==', 'year', 2016]` :)

**Comment by politvs** [comment]
Hi @kriscarle!

I have already implemented a year/month filter; I can even control it with a slider. But I would like to go beyond and filter by place/tags... Since that info look like this:

```
  "extended_info": {
    "tags": "graffitis,nomada",
    "place": "europa,españa,galicia,santiago de compostela"
  }
```

... if I want to filter by tag ~= "nomada" or place ~= "galicia", I have to do a regex query.

So what's exactly your suggestion?

**Comment by kriscarle** [comment]
I'm just saying that since you have the GeoJSON you can modify it however you want, either ahead of time by converting place into place_1, place_2, place_3...  or at runtime with something like:

```js

var updatedData = myGeoJSON.features.map(feature => {
  if(feature.properties.tags.match(someRegex){
     feature.properties.filterme = 1;
  }else{
    feature.properties.filterme = 0;
  }
 return feature;
});

var geoJSONSource = this.map.getSource('my-geojson-source');
geoJSONData.setData(updatedData);

map.on('load', (mapDataEvent){
 if(mapDataEvent.dataType === 'source' && mapDataEvent.isSourceLoaded){
  var queryResult = map.querySourceFeatures('my-geojson-source', {filter: ['==', 'filterme', 1]});
  //...
 }

})
```

Back to your original problem with this repo returning zero results, were you waiting for the source to load before running the query, like in the example above? That is my first thought as to why it gave zero results. I also haven't tested with GeoJSON sources, I'm mostly using vector tiles, but I'm using code extracted directly from mapbox-gl-js, so it should work...

**Comment by politvs** [comment]
Ok.

Since last time I have rewritten part of my code to load all of json files with d3, so I can easily add new properties, but how can I add a new one based on a variable content (d.properties.tag_1, tag_2, tag_3... tag_n)? Anyway I don't like ver much this possible solution since I don't know the number of tags of any given element so I suppose it hardens the filtering somehow.

I have also added an id property, and you pointed out that I can do the search on the plain JSON data filtering then by id... How can that search be done?

Sorry if all that questions are beyond the scope of the original topic, maybe I should ask in stackoverflow or like that...

Anyway, TIA!!

**Comment by politvs** [comment]
Ok, I have halfway solved the property problem:

```
var aTags = dataIn.features.properties.extended_info.tags.split(",");
for (index = 0; index < aTags.length; ++index) {
    dataIn.features = dataIn.features.map(function(d) {
        d.properties["tag_" + index.toString()] = aTags[index];
        return d;
    });
}
```

But this should be done for each feature of the data and

`dataIn.features[i] = dataIn.features[i].map(function(d) {`

throws me a "TypeError: dataIn.features[element].map is not a function[Learn More]".

Can it be done any other way?

**Comment by kriscarle** [comment]
@politvs it should be `dataIn.features.map()` .map() is looping over the items in the array and applying the function to each. 

In general JS devs default to `.map()` unless there is a reason to use `.foreach()` for loops are of course supported too but used more by programmers coming from other languages, not that it is a bad thing :)
https://stackoverflow.com/questions/354909/is-there-a-difference-between-foreach-and-map

You may also want to check out Lodash as it wraps a lot of common operations like this, thought does have a learning curve of its own... https://lodash.com/

**Comment by politvs** [comment]
Yeah, nice, solved it thanks to you!

```
dataIn.features = dataIn.features.map(function(d) {
  var aTags = d.properties.extended_info.tags.split(",");
  for (index = 0; index < aTags.length; ++index) {
    d.properties["tag_" + index.toString()] = aTags[index];
  }
  return d;
});
```
Thanks a lot!

> Since you have access to the raw GeoJSON data, just insert a unique id into the properties of each feature, do the search on the plain JSON data, and then use the filter as supported in the API, ['in', 'id', 1, 2, 3].

How can this be done anyway?
